version: '3.3'
services:
  os-injection:
    container_name: sse-os-injection
    restart: always
    build: OS-Injection
    ports:
      - '3001:3000'

  sql-injection:
    container_name: sse-sql-injection
    restart: always
    build: SQL-Injection
    ports:
      - '3000:3000'
    links:
      - ssedb

  ssedb:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: 'ssedb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'sse'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/data/db

# Names our volume
volumes:
  my-db:
