version: '3.3'
services:
#  app:
#    container_name: node
#    restart: always
#    build: .
#    ports:
#      - '3000:3000'
#    links:
#      - db

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: 'my-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'sse'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/data/db
# Names our volume
volumes:
  my-db:
